version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-prologapp
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prologapp
      POSTGRES_PASSWORD: mecontrata
      POSTGRES_DB: prologapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
