package com.prologapp.desafio.application.enums;

public enum CodigoErro {
    LISTA_VEICULOS_VAZIA("LISTA_VEICULOS_VAZIA"),
    CAMPO_OBRIGATORIO_VAZIO("CAMPO_OBRIGATORIO_VAZIO"),
    VEICULO_NAO_ENCONTRADO("VEICULO_NAO_ENCONTRADO"),
    PARAMETROS_PAGINACAO_INVALIDOS("PARAMETROS_PAGINACAO_INVALIDOS"),
    OBJETO_NULO("OBJETO_NULO"),
    ERRO_AO_SALVAR("ERRO_AO_SALVAR"),
    ERRO_AO_CONTAR_ELEMENTOS("ERRO_AO_CONTAR_ELEMENTOS"),
    ERRO_AO_BUSCAR_ELEMENTOS("ERRO_AO_BUSCAR_ELEMENTOS"),
    PLACA_FORA_DO_PADRAO("PLACA_FORA_DO_PADRAO"),
    VEICULO_JA_CADASTRADO("VEICULO_JA_CADASTRADO"),
    PNEU_JA_CADASTRADO("PNEU_JA_CADASTRADO"),
    POSICAO_OCUPADA("POSICAO_OCUPADA"),
    PNEU_JA_VINCULADO("PNEU_JA_VINCULADO"),
    PRESSAO_FORA_DE_PADRAO("PRESSAO_FORA_DE_PADRAO"),
    PNEU_NAO_ENCONTRADO("PNEU_NAO_ENCONTRADO");

    final String value;

    CodigoErro(String value) {
        this.value = value;
    }
}
